[package]
name = "radicle-tools"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
git2 = "0.13.20"
colored = { version = "1.9" }
atty = { version = "0.2" }
log = { version = "0.4", features = ["std"] }
dialoguer = "0.9.0"
indicatif = "0.16.2"
librad = { path = "../radicle-link/librad" }
rad-clib = { path = "../radicle-link/rad-clib" }
rad-profile = { path = "../radicle-link/rad-profile" }
rad-identities = { path = "../radicle-link/rad-identities" }

[dependencies.radicle-git-ext]
path = "../radicle-link/git-ext"

[workspace]
members = [
  "anchor",
  "account",
  "safe-transaction-client",
  "track",
  "untrack",
  "proof-generator",
  "remote-helper",
  "authorized-keys",
  "rad-auth",
  "rad-init",
  "rad-publish",
]

[patch.crates-io.link-identities]
git = "https://github.com/radicle-dev/radicle-link"
rev = "cc7d348ff79f338c8136903393fedd7f098665d6"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
rev = "cc7d348ff79f338c8136903393fedd7f098665d6"

[patch.crates-io.rad-clib]
git = "https://github.com/radicle-dev/radicle-link"
rev = "cc7d348ff79f338c8136903393fedd7f098665d6"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/erak/thrussh.git"
branch = "generic-agent"
